import Head from 'next/head'
import HelloButton from '../components/HelloButton';
import SignOutButton from '../components/SignOutButton';
import firebase from 'firebase/compat/app';
import 'firebase/compat/auth';
import  firebaseConfig  from '../src/firebaseConfig';
import { getAuth, onAuthStateChanged } from 'firebase/auth';
import SignInButton from '../components/signInButton';
import { useState } from "react";




export default function Home() {
    const [loginState, setLoginState] = useState(false);

    firebase.initializeApp(firebaseConfig);
    const auth = getAuth();
    onAuthStateChanged(auth, (user) => {
    if (user) {
        setLoginState(true);
        console.log(loginState);
        user.providerData.forEach((profile) => {
            console.log("Sign-in provider: " + profile.providerId);
            console.log("  Provider-specific UID: " + profile.uid);
            console.log("  Name: " + profile.displayName);
            console.log("  Email: " + profile.email);
            console.log("  Photo URL: " + profile.photoURL);
            });
    } else {
        console.log(loginState);
        setLoginState(false)
        console.log("not login");
    }
    });

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HelloButton />
            <SignOutButton loginState={loginState}/>
            <SignInButton loginState={loginState}/>
        </>
    );
}