import Head from 'next/head'
import SignInButton from '../components/SignInButton';
import SignOutButton from '../components/SignOutButton';
import PostList from '../components/PostList';
import BottomAppBar from '../components/AppBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignInButton />
      <SignOutButton />
      <PostList />
      <BottomAppBar />
    </>
  );
}