import Head from 'next/head'
import router from 'next/router';
import GoogleSignInButton from '../components/GoogleSignInButton';
import { useSignInState } from '../contexts/SignInStateProvider';

export default function Index() {
  const { userState } = useSignInState();
  if(userState) router.push('/home');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GoogleSignInButton />
    </>
  );
}
