import { ThemeProvider } from "@emotion/react";
import { Typography } from "@mui/material";
import { Box } from "@mui/system";
import Head from "next/head"
import router from "next/router";
import GoogleSignInButton from "../components/GoogleSignInButton";
import { useSignInState } from "../contexts/SignInStateProvider";
import { LoginTopFont } from "../src/theme";
import theme from "../src/theme";

export default function Index() {
  const { userState } = useSignInState();
  if(userState && router.pathname !== "/home") router.push("/home");
  return (
    <>
      <Head>
        <title>MOMENT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <ThemeProvider theme={LoginTopFont}>
        <Typography sx={{display: "flex", justifyContent: "center", mt: "100px", color: "#5094cc", fontSize: 75}} >
          MOMENT
        </Typography>
      </ThemeProvider>
      <Typography sx={{display: "flex", justifyContent: "center" }} variant="body1">
          あなたが見つけたスポットを投稿しよう
        </Typography>
      <Box sx={{display: "flex", justifyContent: "center", mt: "50px" }} >
        <GoogleSignInButton />
      </Box>
      
    </>
  );
}
