import Head from 'next/head'
import HelloButton from '../components/HelloButton';
import ButtomAppBar from '../components/BottomAppBar';
import GitHubUser from '../components/GitHubUser';
import GoogleLoginButton from '../components/FirebaseAuthGoogle';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GoogleLoginButton />
    </>
  );
}
